#!/usr/bin/env node
// migrate-doc.mjs — convert the existing VitePress handbook (doc/*.md) into a
// D1 seed file (app/db/seed/0002_seed.sql). PURE NODE.
//
// Body is stored as MARKDOWN VERBATIM (the Astro render pipeline handles :::,
// [[TOC]] and mermaid at render time). The leading `# H1` becomes the title and
// is stripped from the body. IA metadata (section/sort/nav_label) is seeded from
// the VitePress sidebar, never inferred.
//
// Also seeds two test users (editor + reader personas). No access groups are
// seeded — the restricted (group-gated) visibility level is unused by default.
//
// Usage:  node app/db/migrate-doc.mjs

import { readFile, writeFile, mkdir } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url)); // app/db
const repoRoot = path.resolve(here, "..", "..");
const docDir = path.join(repoRoot, "doc");
const outDir = path.join(here, "seed");
const outFile = path.join(outDir, "0002_seed.sql");

// Mirror of doc/.vitepress/config.mts sidebar.
const PAGE_META = {
  "what-is-handbook": { section: "About", nav_label: "What is Handbook?", visibility: "public" },
  strategy: { section: "About", nav_label: "Strategy", visibility: "internal" },
  "code-of-conduct": {
    section: "People & Culture",
    nav_label: "Code of Conduct",
    visibility: "public",
  },
  "talent-acquisition": {
    section: "People & Culture",
    nav_label: "Talent Acquisition",
    visibility: "internal",
  },
  "on-boarding": { section: "Guideline", nav_label: "On-boarding Guide", visibility: "internal" },
  "development-guide": {
    section: "Guideline",
    nav_label: "Development Guide",
    visibility: "internal",
  },
  "predefining-non-functional-requirements": {
    section: "Guideline",
    nav_label: "Non-functional Requirements",
    visibility: "internal",
  },
  "technical-glossary": {
    section: "Guideline",
    nav_label: "Technical Glossary",
    visibility: "internal",
  },
  "sheq-policy": { section: "Policies", nav_label: "SHEQ Policy", visibility: "internal" },
  "security-policy": {
    section: "Policies",
    nav_label: "Security Policy",
    visibility: "internal",
  },
};
// Test personas (POC). Real membership comes from Google Groups pre-prod.
const GROUPS = [];
const USERS = [
  { email: "editor@osbrjp.com", role: "editor", name: "Editor" },
  { email: "reader@osbrjp.com", role: "reader", name: "Reader" },
];
const USER_GROUPS = [];

export function extractTitle(md, slug) {
  const m = md.match(/^\s*#\s+(.+?)\s*$/m);
  return m ? m[1].trim() : slugToTitle(slug);
}
export function stripLeadingH1(md) {
  return md.replace(/^\s*#\s+.+?\r?\n+/, "");
}
export function slugToTitle(slug) {
  return slug
    .split("-")
    .filter(Boolean)
    .map((w) => w[0].toUpperCase() + w.slice(1))
    .join(" ");
}
const sql = (v) => (v === null || v === undefined ? "NULL" : `'${String(v).replace(/'/g, "''")}'`);

async function buildPages() {
  // Iterate PAGE_META in declaration order so section + within-section order
  // matches the original VitePress sidebar (config.mts), not alphabetical.
  const pages = [];
  for (const slug of Object.keys(PAGE_META)) {
    const meta = PAGE_META[slug];
    let raw;
    try {
      raw = await readFile(path.join(docDir, `${slug}.md`), "utf8");
    } catch {
      continue; // skip if the markdown file is missing
    }
    pages.push({
      slug,
      title: extractTitle(raw, slug),
      section: meta.section,
      nav_label: meta.nav_label || slugToTitle(slug),
      visibility: meta.visibility,
      groups: meta.groups || [],
      body: stripLeadingH1(raw).trim(),
    });
  }
  // Global sequential sort → ORDER BY sort groups sections in declaration order.
  pages.forEach((p, i) => {
    p.sort = (i + 1) * 10;
  });
  return pages;
}

async function main() {
  const pages = await buildPages();
  const lines = [];
  lines.push("-- Generated by app/db/migrate-doc.mjs — do not edit by hand.");
  lines.push("BEGIN TRANSACTION;");

  lines.push("\n-- groups");
  for (const g of GROUPS)
    lines.push(`INSERT INTO groups (key, label) VALUES (${sql(g.key)}, ${sql(g.label)});`);

  lines.push("\n-- users");
  for (const u of USERS)
    lines.push(
      `INSERT INTO users (email, role, name) VALUES (${sql(u.email.toLowerCase())}, ${sql(u.role)}, ${sql(u.name)});`,
    );

  lines.push("\n-- user_groups");
  for (const ug of USER_GROUPS)
    lines.push(
      `INSERT INTO user_groups (email, group_id) SELECT ${sql(ug.email.toLowerCase())}, g.id FROM groups g WHERE g.key=${sql(ug.group)};`,
    );

  lines.push("\n-- pages (published)");
  for (const p of pages) {
    lines.push(
      `INSERT INTO pages (slug, title, section, nav_label, sort, visibility, status, body) VALUES (${sql(p.slug)}, ${sql(p.title)}, ${sql(p.section)}, ${sql(p.nav_label)}, ${p.sort}, ${sql(p.visibility)}, 'published', ${sql(p.body)});`,
    );
  }

  lines.push("\n-- page_groups (restricted -> groups)");
  for (const p of pages) {
    for (const gk of p.groups) {
      lines.push(
        `INSERT INTO page_groups (page_id, group_id) SELECT p.id, g.id FROM pages p, groups g WHERE p.slug=${sql(p.slug)} AND g.key=${sql(gk)};`,
      );
    }
  }

  lines.push("\nCOMMIT;\n");
  await mkdir(outDir, { recursive: true });
  await writeFile(outFile, lines.join("\n"), "utf8");

  const byVis = {};
  for (const p of pages) byVis[p.visibility] = (byVis[p.visibility] || 0) + 1;
  console.log(
    `Wrote ${pages.length} pages + ${USERS.length} users + ${GROUPS.length} group -> ${path.relative(repoRoot, outFile)}`,
  );
  console.log("  visibility:", byVis);
}

if (import.meta.url === pathToFileURL(process.argv[1] || "").href) {
  main().catch((e) => {
    console.error(e);
    process.exit(1);
  });
}
